### ISSUE TITLE
Requesting Pre-processing code for video to sound extractor

### ISSUE THREAD

**Issue by zaltiner** [bjlfzs/Certifiable-Robust-Multi-modal-Training#2]
Hello,

Thank you for your sincere work, I really appreciate your research contribution.

While I was trying to reproduce the code, I encounter an issue for extracting video to sound during pre-processing. You have already shared the code to extract video frames, however I could not find the sound extractor. Is it possible for you to share the code for the video to sound extractor as well?

Thank you.

**Comment by bjlfzs** [comment]
Hi, thank you for your attention. We have now uploaded the sound extractor code to our repository.
